services:
  docs:
    image: cookable_local_docs
    container_name: cookable_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./cookable:/app/cookable:z
    ports:
      - '9000:9000'
    command: /start-docs
